import Token from "./Token.util";

export type TTokenRule = {
	id: ETokenTypes
	regexp?: RegExp
	types?: TTokenTypes
	extendTokenTypes?: (token: Token, tokens: Token[], text: string, index: number) => ETokenTypes[]
};

export type TTokenTypes = Set<string extends ETokenTypes ? string : never>;

export type TTokenizerConfig = {
	rules: TTokenRule[]
	keywords: Set<string>
};

export enum ETokenTypes {
	PUNCTUATION_NEW_LINE              = "PUNCTUATION_NEW_LINE",
	PUNCTUATION_TAB                   = "PUNCTUATION_TAB",
	PUNCTUATION_WHITE_SPACE           = "PUNCTUATION_WHITE_SPACE",
	PUNCTUATION_APOSTROPH             = "PUNCTUATION_APOSTROPH",
	PUNCTUATION_QUOTETION_MARK        = "PUNCTUATION_QUOTATION_MARK",

	PUNCTUATION_LEFT_ROUND_BRACKET    = "PUNCTUATION_LEFT_ROUND_BRACKET",
	PUNCTUATION_LEFT_SQUARE_BRACKET   = "PUNCTUATION_LEFT_SQUARE_BRACKET",
	PUNCTUATION_LEFT_BRACES           = "PUNCTUATION_LEFT_BRACES",
	PUNCTUATION_RIGHT_ROUND_BRACKET   = "PUNCTUATION_RIGHT_ROUND_BRACKET",
	PUNCTUATION_RIGHT_BRACES          = "PUNCTUATION_RIGHT_BRACES",
	PUNCTUATION_RIGHT_SQUARE_BRACKET  = "PUNCTUATION_RIGHT_SQUARE_BRACKET",
	
	PUNCTUATION_PLUS                  = "PUNCTUATION_PLUS",
	PUNCTUATION_MINUS                 = "PUNCTUATION_MINUS",
	PUNCTUATION_MUL                   = "PUNCTUATION_MUL",
	PUNCTUATION_DIV                   = "PUNCTUATION_DIV",
	PUNCTUATION_COMMA                 = "PUNCTUATION_COMMA",
	PUNCTUATION_DOT                   = "PUNCTUATION_DOT",
	PUNCTUATION_SEMI_COLON            = "PUNCTUATION_SEMI_COLON",
	PUNCTUATION_COLON                 = "PUNCTUATION_COLON",
	PUNCTUATION_ASSIGN                = "PUNCTUATION_ASSIGN",
	PUNCTUATION_EQUAL                 = "PUNCTUATION_EQUAL",
	PUNCTUATION_SMALLER_THEN          = "PUNCTUATION_SMALLER_THEN",
	PUNCTUATION_SMALLER_OR_EQUAL_THEN = "PUNCTUATION_SMALLER_OR_EQUAL_THEN",
	PUNCTUATION_BIGGER_THEN           = "PUNCTUATION_BIGGER_THEN",
	PUNCTUATION_BIGGER_OR_EQUAL_THEN  = "PUNCTUATION_BIGGER_OR_EQUAL_THEN",
	
	TEXT                              = "TEXT",
	UNREACHABLE                       = "UNREACHABLE",
	FUNCTION_IDENTIFIER               = "FUNCTION_IDENTIFIER",

	NUMBER_LITERAL                    = "NUMBER_LITERAL",
	
	SPECIFIC_STRING_LITERAL           = "SPECIFIC_STRING_LITERAL",
	SPECIFIC_KEYWORD                  = "SPECIFIC_KEYWORD",
	SPECIFIC_IDENTIFIER               = "SPECIFIC_IDENTIFIER"
};